import { ResumeData, CoverLetterData } from './types';

export const SAMPLE_RESUME: ResumeData = {
  title: 'Senior Software Engineer Resume',
  personalInfo: {
    fullName: 'Alex Morgan',
    jobTitle: 'Senior Full-Stack Engineer',
    email: 'alex.morgan@email.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    website: 'https://alexmorgan.dev',
    linkedin: 'linkedin.com/in/alexmorgan',
    github: 'github.com/alexmorgan',
  },
  summary:
    'Results-driven Senior Full-Stack Engineer with 7+ years of experience designing, architecting, and scaling distributed cloud applications. Proven track record of spearheading microservice migrations, cutting latency by 38%, and mentoring engineering teams. Passionate about developer velocity, high-reliability architectures, and clean code practices.',
  workExperience: [
    {
      id: 'exp-1',
      company: 'Apex Cloud Systems',
      position: 'Senior Software Engineer',
      location: 'San Francisco, CA',
      startDate: '2021-03',
      endDate: 'Present',
      current: true,
      bullets: [
        'Architected high-throughput event-driven microservices in Go and TypeScript, processing 45M+ daily API transactions with 99.99% uptime.',
        'Spearheaded the migration from a monolithic backend to modular cloud services on AWS/Kubernetes, reducing server infrastructure costs by $180,000 annually.',
        'Mentored 6 junior and mid-level engineers through bi-weekly pair programming and comprehensive code reviews, increasing team velocity by 25%.',
        'Implemented automated CI/CD deployment pipelines with GitHub Actions, trimming mean deployment cycle time from 45 minutes to 7 minutes.',
      ],
    },
    {
      id: 'exp-2',
      company: 'DataVanguard Solutions',
      position: 'Software Engineer',
      location: 'San Jose, CA',
      startDate: '2018-06',
      endDate: '2021-02',
      current: false,
      bullets: [
        'Engineered responsive React and Next.js customer-facing dashboards delivering real-time analytics for 120,000+ active enterprise users.',
        'Optimized PostgreSQL database query execution plans and caching with Redis, improving p95 query response latency by 42%.',
        'Collaborated with product managers and UX designers to establish an accessible UI design system compliant with WCAG 2.1 AA standards.',
      ],
    },
    {
      id: 'exp-3',
      company: 'NovaTech Labs',
      position: 'Associate Developer',
      location: 'Berkeley, CA',
      startDate: '2017-01',
      endDate: '2018-05',
      current: false,
      bullets: [
        'Developed modular RESTful APIs using Node.js, Express, and MongoDB for e-commerce clients.',
        'Authored over 200 unit and end-to-end integration tests using Jest and Cypress, elevating test coverage from 58% to 89%.',
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      school: 'University of California, Berkeley',
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      location: 'Berkeley, CA',
      startDate: '2013-09',
      endDate: '2017-05',
      gpa: '3.85 / 4.0',
      honors: 'Dean’s Honors List (6 consecutive semesters), Cum Laude',
    },
  ],
  skills: {
    technical: [
      'TypeScript',
      'JavaScript (ES6+)',
      'Go',
      'Python',
      'React.js',
      'Next.js',
      'Node.js',
      'GraphQL',
      'PostgreSQL',
      'Redis',
    ],
    tools: [
      'AWS (ECS, S3, RDS, Lambda)',
      'Docker',
      'Kubernetes',
      'Git',
      'GitHub Actions',
      'Terraform',
      'Datadog',
      'Jest',
    ],
    soft: [
      'Cross-functional Leadership',
      'Agile / Scrum',
      'System Architecture',
      'Technical Mentorship',
      'Root-Cause Analysis',
      'Stakeholder Communication',
    ],
    languages: ['English (Native)', 'Spanish (Professional Working)'],
  },
  projects: [
    {
      id: 'proj-1',
      name: 'StreamSync Distributed Cache',
      description:
        'Open-source in-memory caching engine written in Go supporting consistent hashing and Raft consensus.',
      link: 'https://github.com/alexmorgan/streamsync',
      technologies: 'Go, Raft, gRPC, Docker',
      bullets: [
        'Benchmarked at 85,000 read ops/sec with sub-millisecond p99 latency under heavy concurrent loads.',
        'Earned 1,400+ GitHub stars and adopted by 12 production developer teams.',
      ],
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      name: 'AWS Certified Solutions Architect – Professional',
      issuer: 'Amazon Web Services',
      date: '2023-04',
      url: 'https://aws.amazon.com/verification',
    },
    {
      id: 'cert-2',
      name: 'Certified Kubernetes Administrator (CKA)',
      issuer: 'Cloud Native Computing Foundation (CNCF)',
      date: '2022-08',
      url: 'https://cncf.io/certification',
    },
  ],
  awards: [
    {
      id: 'award-1',
      title: 'Innovator of the Year Award',
      issuer: 'Apex Cloud Systems',
      date: '2023-12',
      description: 'Recognized for conceiving and executing the cost-reduction cloud modernization initiative.',
    },
  ],
  customSections: [],
  sectionOrder: [
    'personalInfo',
    'summary',
    'workExperience',
    'education',
    'skills',
    'projects',
    'certifications',
    'awards',
  ],
  style: {
    template: 'ats',
    primaryColor: '#0f172a',
    fontFamily: 'sans',
    fontSize: 'normal',
    lineSpacing: 'normal',
  },
};

export const BLANK_RESUME: ResumeData = {
  title: 'Untitled Resume',
  personalInfo: {
    fullName: '',
    jobTitle: '',
    email: '',
    phone: '',
    location: '',
    website: '',
    linkedin: '',
    github: '',
  },
  summary: '',
  workExperience: [
    {
      id: 'exp-1',
      company: '',
      position: '',
      location: '',
      startDate: '',
      endDate: '',
      current: false,
      bullets: [''],
    },
  ],
  education: [
    {
      id: 'edu-1',
      school: '',
      degree: '',
      field: '',
      location: '',
      startDate: '',
      endDate: '',
      gpa: '',
      honors: '',
    },
  ],
  skills: {
    technical: [],
    tools: [],
    soft: [],
    languages: [],
  },
  projects: [],
  certifications: [],
  awards: [],
  customSections: [],
  sectionOrder: [
    'personalInfo',
    'summary',
    'workExperience',
    'education',
    'skills',
    'projects',
    'certifications',
    'awards',
  ],
  style: {
    template: 'ats',
    primaryColor: '#0f172a',
    fontFamily: 'sans',
    fontSize: 'normal',
    lineSpacing: 'normal',
  },
};

export const SAMPLE_COVER_LETTER: CoverLetterData = {
  personalInfo: {
    fullName: 'Alex Morgan',
    email: 'alex.morgan@email.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    linkedin: 'linkedin.com/in/alexmorgan',
  },
  recipient: {
    hiringManager: 'Hiring Team',
    companyName: 'Starlight Tech Inc.',
    companyAddress: '100 Market Street, San Francisco, CA',
    jobTitle: 'Staff Backend Infrastructure Engineer',
    department: 'Platform Engineering',
  },
  date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
  greeting: 'Dear Hiring Team,',
  openingParagraph:
    'I am writing to express my enthusiastic interest in the Staff Backend Infrastructure Engineer position at Starlight Tech Inc. With over seven years of hands-on experience designing high-throughput distributed systems, orchestrating microservices migrations, and optimizing cloud architectures on AWS and Kubernetes, I am eager to help expand Starlight’s core platform infrastructure.',
  bodyParagraphs: [
    'In my current role as Senior Software Engineer at Apex Cloud Systems, I architected event-driven microservices that handle over 45 million transactions daily with 99.99% availability. Additionally, I spearheaded a multi-region infrastructure overhaul that trimmed annual hosting overhead by $180,000 while reducing p95 response times by 38%.',
    'Beyond technical architecture, I believe strong engineering cultures are built on collaboration, continuous automation, and mentorship. I have guided 6 engineers into senior roles, standardized code review guidelines, and cut deployment cycles from 45 minutes to 7 minutes with automated CI/CD pipelines. Starlight’s focus on high reliability and developer velocity resonates deeply with my professional values.',
  ],
  closingParagraph:
    'I welcome the opportunity to discuss how my technical leadership, distributed systems expertise, and passion for performance optimization can deliver immediate value to Starlight Tech Inc. Thank you for your time and consideration.',
  signoff: 'Sincerely,',
};
